/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3QCmQoi3MoV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"
import { Yeseva_One } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'
import {DirectorInfo} from './directorinfo'
const yesevaFont = Yeseva_One({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
});

const cormorantFont = Cormorant_Garamond({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
});
export function AboutUs() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in">
        <div className="container px-4 md:px-6 mx-auto ">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-800 px-3 py-1 text-sm">Research Lab</div>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none animate-fade-up">
                  About Us!
                </h1>
                <p className="max-w-[600px] text-gray-400 md:text-xl animate-fade-up">
                  Hosted by Illinois Institute of Technology
                </p>
              </div>
            </div>
            <div className="flex items-center justify-center animate-fade-in">
              <img
                alt="iconSense"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-contain object-center"
                style={{ width: '350px', height: 'auto' }} // Adjusted width and height
                src="https://iconsense.iit.edu/images/logo2.png"
              />
            </div>
          </div>
        </div>
      </section>

      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-800 dark:bg-gray-800 animate-fade-in">
        <DirectorInfo></DirectorInfo>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in ">
        <div className="container px-4 md:px-6 mx-auto ">
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl animate-fade-up">
                About iConSenSe Research Lab
              </h2>
              <p className="max-w-[700px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed animate-fade-up">
              The mission of iConSenSe Lab is to incorporate computing and sensing technologies in construction engineering and management activities, there by bring construction project participants together and to perform efficient operations in the projects through the use of innovative information technologies. We recognize that communication amongst actors is irrespective of the fact that they may belong to different organizations, have different backgrounds, or be located in different parts of the globe
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl animate-fade-up">
                Awards and Recognitions
              </h3>
              <ul className="space-y-2 text-gray-400 animate-fade-up">
                <li>
                  - Awarded the prestigious Nobel Prize in Chemistry in 2018 for groundbreaking work in materials
                  science.
                </li>
                <li>
                  - Recognized as one of the Top 10 Research Institutes by Scientific American magazine in 2020.
                </li>
                <li>
                  - Received the National Science Foundations prestigious Transformative Research Award in 2021 for
                  our work in renewable energy.
                </li>
              </ul>
            </div>
            <div className="space-y-2">
              <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl animate-fade-up">Key Partnerships</h3>
              <ul className="space-y-2 text-gray-400 animate-fade-up">
                <li>
                  - Collaborating with the University of California, Berkeley on a multi-year project to develop
                  advanced materials for next-generation batteries.
                </li>
                <li>
                  - Partnering with the Bill & Melinda Gates Foundation to investigate new approaches to global health
                  challenges.
                </li>
                <li>
                  - Working with leading technology companies like Google and Microsoft on AI-powered research tools and
                  data analytics platforms.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
