/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lahuA8jZbUu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { JSX, SVGProps } from "react"

export function DirectorInfo() {
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="flex items-center justify-center md:justify-start">
        <img
          alt="Director Photo"
          className="rounded-l-lg object-cover max-w-full h-auto md:h-full"
          src="https://iconsense.iit.edu/professors/IvanMutis.jpg"
          style={{ maxWidth: '400px' }}
        />
      </div>
      <div className="flex flex-col justify-between p-6 bg-gray-900 text-gray-50 rounded-r-lg h-full">
        <div className="space-y-2">
          <h3 className="text-2xl font-bold">Dr. Ivan Mutis</h3>
          <p className="text-gray-400">Director, iConSense</p>
        </div>
        <p className="text-sm leading-relaxed">
          Dr. Ivan Mutis is the director of the progam who is a Ph.D. holder from the University of Florida, is a leading expert in construction informatics. With a focus on technologies like BIM and Virtual Design Construction, his work drives collaboration and innovation in construction projects. As a prolific author and active member of professional associations, Dr. Mutis&#39;s contributions have significantly influenced the field, particularly in knowledge management and sustainable construction technologies.
        </p>
        <div className="flex items-center gap-4">
          <a className="text-gray-400 hover:text-gray-300" href="#">
            <TwitterIcon className="h-5 w-5" />
            <span className="sr-only">Twitter</span>
          </a>
          <a className="text-gray-400 hover:text-gray-300" href="#">
            <LinkedinIcon className="h-5 w-5" />
            <span className="sr-only">LinkedIn</span>
          </a>
        </div>
      </div>
    </div>

  )
}

function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
