/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HMXtbSAQMFz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function ProfileInfo() {
  return (
    <Card className="w-full max-w-sm hover:scale-105 transition-transform duration-300 ease-in-out cursor-pointer">
      <div className="relative group">
        <img
          alt="Team Member"
          className="aspect-square object-cover rounded-t-lg group-hover:opacity-80 transition-opacity"
          height={400}
          src="https://iconsense.iit.edu/professors/IvanMutis.jpg"
          width={400}
        />
        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4 rounded-t-lg group-hover:opacity-0 transition-opacity">
          <div className="flex items-center justify-between">
            <div className="space-y-1 text-white">
              <h4 className="text-lg font-medium">Dr. Ivan Mutis</h4>
              <p className="text-sm">Director </p>
            </div>
            <div className="flex items-center gap-2">
              <Link aria-label="LinkedIn" href="https://google.com">
                <LinkedinIcon className="h-5 w-5 text-white" />
              </Link>
              <Link aria-label="Twitter" href="#">
                <TwitterIcon className="h-5 w-5 text-white" />
              </Link>
              <Link aria-label="GitHub" href="#">
                <GithubIcon className="h-5 w-5 text-white" />
              </Link>
            </div>
          </div>
        </div>
        <div className="absolute inset-0 bg-black/50 rounded-t-lg opacity-0 group-hover:opacity-100 transition-opacity">
          <div className="flex h-full w-full items-center justify-center">
            <div className="space-y-2 text-white text-center">
              <h4 className="text-lg font-medium">Dr. Ivan Mutis</h4>
              <p className="text-sm">Associate Professor</p>
              <div className="flex items-center gap-2">
                <Link aria-label="LinkedIn" href="https://google.com">
                  <LinkedinIcon className="h-5 w-5 text-white" />
                </Link>
                <Link aria-label="Twitter" href="#">
                  <TwitterIcon className="h-5 w-5 text-white" />
                </Link>
                <Link aria-label="GitHub" href="#">
                  <GithubIcon className="h-5 w-5 text-white" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
      <CardContent className="p-6">
        <div className="mt-4 flex items-center justify-between">
          <div className="space-y-1">
            <h5 className="text-sm font-medium">Illinois Institute of Technology</h5>
            <p className="text-sm text-gray-500 dark:text-gray-400">Constru Science</p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
