/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YERzAbBJMOE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { JSX, SVGProps } from "react"

export function ResearchProject() {
  return (
    <>
      
      <section className="w-full pt-12 md:pt-24 lg:pt-32 bg-gradient-to-b from-gray-100 to-gray-50 dark:from-gray-900 dark:to-gray-800">
        <div className="container space-y-10 xl:space-y-16 mx-auto ">
          <div className="flex flex-col items-center space-y-6 text-center">
            <div className="space-y-3">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                Discover Our Groundbreaking Research
              </h1>
              <p className="mx-auto max-w-[800px] text-gray-600 md:text-xl dark:text-gray-400">
                Explore the latest innovations and breakthroughs from our world-renowned research teams. From
                sustainable energy to cutting-edge AI, we&#39;re pushing the boundaries of what&#39;s possible.
              </p>
              <br></br>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 px-4 md:px-6 mx-auto ">
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 1"
              className="w-full h-60 object-cover"
              height="240"
              src="https://iconsense.iit.edu/projects/Mixed%20Reality%20for%20Engineering%20Design%20Interpretation/home/mrfe.jpeg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Mixed Reality for Engineering Design Interpretation</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                one line information about the proje
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  Mixed Reality
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 2"
              className="w-full h-60 object-cover"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Advancements in Robotics</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                Developing cutting-edge robotic systems to revolutionize industries.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  Robotics
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 3"
              className="w-full h-60 object-cover"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Artificial Intelligence</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                Pushing the boundaries of AI to solve complex problems.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  AI
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 4"
              className="w-full h-60 object-cover"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Biomedical Breakthroughs</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                Advancing medical research to improve human health and wellbeing.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  Biomedical
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 5"
              className="w-full h-60 object-cover"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Materials Science</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                Developing innovative materials with unique properties.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  Materials
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 dark:bg-gray-950">
            <img
              alt="Project 6"
              className="w-full h-60 object-cover"
              height="240"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/240",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-6">
              <h3 className="text-xl font-semibold">Quantum Computing</h3>
              <p className="text-gray-600 dark:text-gray-400 mt-2">
                Exploring the potential of quantum technology to solve complex problems.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Badge className="bg-gray-100 dark:bg-gray-800" variant="outline">
                  Quantum
                </Badge>
                <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-950">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="space-y-3 text-center md:text-left">
              <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">
                Search Our Research Projects
              </h2>
              <p className="text-gray-600 dark:text-gray-400">Explore our latest breakthroughs and innovations.</p>
            </div>
            <div className="w-full md:w-auto">
              <form className="relative">
                <Input className="pr-12" placeholder="Search projects..." type="search" />
                <Button className="absolute right-1 top-1/2 -translate-y-1/2" type="submit" variant="ghost">
                  <SearchIcon className="h-5 w-5" />
                  <span className="sr-only">Search</span>
                </Button>
              </form>
            </div>
          </div>
        </div>
      </section> */}
      </>
  )
}

function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
